name: Build ARM64 MacOS Profile
on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '*.yaml'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '*.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Build
        run:  sudo -E ./make macos_arm64
